<?php use Core\FH;
  use Core\H;
?>

<?php $this->setSiteTitle('Process Payment');?>
<?php $this->start('body')?>
<?php
  include_once('OAuth.php');

  $token = $params = NULL;
  $consumer_key = PESAPAL_CONSUMER_KEY;//Register a merchant account on
                     //demo.pesapal.com and use the merchant key for testing.
                     //When you are ready to go live make sure you change the key to the live account
                     //registered on www.pesapal.com!
  $consumer_secret = PESAPAL_CONSUMER_SECRET;// Use the secret from your test
                     //account on demo.pesapal.com. When you are ready to go live make sure you
                     //change the secret to the live account registered on www.pesapal.com!
  $signature_method = new OAuthSignatureMethod_HMAC_SHA1();
  $iframelink = 'https://www.pesapal.com/api/PostPesapalDirectOrderV4';//change to
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!
  $currency = FH::getCurrencyAndCode()['currency'];
  $currencyCode = FH::getCurrencyAndCode()['currencyCode'];
  $currencyExRate = FH::getCurrencyAndCode()['currencyExRate'];

  $names = $this->tx->name;
  $namearry = explode(" ", $names);
  $namelen = sizeof($namearry);
  if($namelen > 2 ) {
    $lastname = $namearry[1] . ' ' . $namearry[2];
  } elseif ($namelen == 2) {
    $lastname = $namearry[1];
  } else {
    $lastname = '';
  }

  //get form details
  $chargetotal = ceil(($this->grandTotal)*$currencyExRate);
  //echo "<br>";

  if($chargetotal > 1000){
  ?>
    <div class="row col-md-12 d-flex justify-content-center" >
      <div class="col-md-6">
        <h3>Process Payment</h3>
        <p class="font-weight-bold"> For financial security reasons any amount above ksh 1,000/- kindly contact us via email address <span class="font-italic text-info">sales@ivystudio.com </span> or call us at <span class="font-italic text-info">+25479634018</span>, thank you. </p>
        <p>
          <a id="url" href="<?=PROOT?>cart/index" class="btn btn-lg btn-primary btn-block">Proceed To View Cart</a>
        </p>
      </div>

      <div class="col-md-6"><?php $this->partial('cart','product_preview')?></div>
    </div>
  <?php
  } else {
    //echo $amount = number_format(70000,2);//format amount to 2 decimal places
    $amount = number_format($chargetotal,2);//format amount to 2 decimal places
    //$amount = number_format(500,2);//format amount to 2 decimal places
    $desc = 'Ivyartic Studio';
    $type = 'MERCHANT'; //default value = MERCHANT
    $reference = $this->cartId;//unique order id of the transaction, generated by merchant
    $first_name = $namearry[0]; //[optional]
    $last_name = $lastname; //[optional]
    $email = $this->tx->email;
    $phonenumber = $this->tx->phone; //ONE of email or phonenumber is required
    $street1 = $this->tx->shipping_address1; //ONE of email or phonenumber is required

     $callback_url = 'https://www.ivyarticstudio.com/cart/paymentstatus/'; //redirect url, the page that will handle the response from pesapal.
  $post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchemainstance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
     $post_xml = htmlentities($post_xml);
     $consumer_key = PESAPAL_CONSUMER_KEY;
     $consumer_secret = PESAPAL_CONSUMER_SECRET;
     $consumer = new OAuthConsumer($consumer_key, $consumer_secret);

     //post transaction to pesapal
     $iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET",
     $iframelink, $params);
     $iframe_src->set_parameter("oauth_callback", $callback_url);
     $iframe_src->set_parameter("pesapal_request_data", $post_xml);
     $iframe_src->sign_request($signature_method, $consumer, $token);

  ?>
  <div class="row">
    <div class="col-md-9">
      <h3>Process Payment</h3>
      <iframe src="<?php echo $iframe_src;?>" width="100%" height="720px" scrolling="auto" frameBorder="0"> <p>Unable to load the payment page</p> </iframe>
    </div>

    <div class="col-md-3"><?php $this->partial('cart','product_preview')?></div>
  </div>
<?php } ?>
 <?php $this->end() ?>
