<?php $this->setSiteTitle("PesaPal")?>
<?php $this->start('head') ?>

<?php $this->end() ?>
<?php $this->start('body')?>
<?php
  include_once('OAuth.php');

  $token = $params = NULL;
  $consumer_key = PESAPAL_CONSUMER_KEY;//Register a merchant account on
                     //demo.pesapal.com and use the merchant key for testing.
                     //When you are ready to go live make sure you change the key to the live account
                     //registered on www.pesapal.com!
  $consumer_secret = PESAPAL_CONSUMER_SECRET;// Use the secret from your test
                     //account on demo.pesapal.com. When you are ready to go live make sure you
                     //change the secret to the live account registered on www.pesapal.com!
  $signature_method = new OAuthSignatureMethod_HMAC_SHA1();
  $iframelink = 'https://demo.pesapal.com/api/PostPesapalDirectOrderV4';//change to
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!
   //get form details<br>$amount = $_POST['amount'];
   $amount = '699999';//format amount to 2 decimal places
   $amount = number_format($amount, 2);
   $desc = 'Goods one';
   $type = 'MERCHANT'; //default value = MERCHANT
   $reference = 'cart001';//unique order id of the transaction, generated by merchant
   $first_name = 'Anthony'; //[optional]
   $last_name = 'Ngugi'; //[optional]
   $email = 'info@ivyarticstudio.com';
   $phonenumber = '0728519998'; //ONE of email or phonenumber is required

  $callback_url = 'https://www.ivyarticstudio.com/cart/checkout'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchemainstance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
$post_xml = htmlentities($post_xml);

  $consumer = new OAuthConsumer($consumer_key, $consumer_secret);

 //post transaction to pesapal
  $iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET",
  $iframelink, $params);
  $iframe_src->set_parameter("oauth_callback", $callback_url);
  $iframe_src->set_parameter("pesapal_request_data", $post_xml);
  $iframe_src->sign_request($signature_method, $consumer, $token);
?>
<iframe src="<?php echo $iframe_src;?>" width="100%" height="720px" scrolling="auto" frameBorder="0"> <p>Unable to load the payment page</p> </iframe>
